### ISSUE TITLE
Reserved Keyword (try) in Generated Bindings

### ISSUE THREAD

**Issue by theduke** [foniod/redbpf#219]
I'm trying to compile a simple bpf program.

```rust
#![no_std]
#![no_main]

use redbpf_probes::xdp::{
    prelude::{program, xdp},
    XdpAction, XdpContext, XdpResult,
};

program!(0xFFFFFFFE, "GPL");

#[xdp]
fn sockfilter(ctx: XdpContext) -> XdpResult {
    //bpf_trace_printk(b"WARDEN SOCKOP\0");
    Ok(XdpAction::Pass)
}
```

Running `cargo bpf build --target-dir=../target` results in the following Rust error:

```
error: expected identifier, found reserved keyword `try`
     --> /home/theduke/dev/github.com/theduke/warden/target/bpf/release/build/redbpf-probes-d75a45e5e68ca0ba/out/gen_bindings.rs:40824:9
      |
40824 |     pub try: kunit_try_catch_func_t,
      |         ^^^ expected identifier, found reserved keyword
      |
help: you can escape reserved keywords to use them as identifiers
      |
40824 |     pub r#try: kunit_try_catch_func_t,
      |         ~~~~~

error: could not compile `redbpf-probes` due to previous error
error: failed to compile the `sockop' program
```

The offending code is here:

```rust
pub struct kunit_try_catch {
    pub test: *mut kunit,
    pub try_completion: *mut completion,
    pub try_result: ::cty::c_int,
    pub r#try: kunit_try_catch_func_t,
    pub catch: kunit_try_catch_func_t,
    pub context: *mut ::cty::c_void,
}
```

## Environment:

`rustc 1.56.1`
`llvm 13`
`cargo bpf --version`: `cargo-bpf 2.1.0`
Kernel: `5.10.78`

**Comment by rhdxmr** [comment]
@theduke 
Thanks for filing this issue.

I just found this issue: https://github.com/rust-lang/rust-bindgen/pull/2112

16 days ago, @fionera had reported that `try` keyword is not properly escaped by bindgen and fixed the problem.

I've never realize this problem because my `gen_bindings.rs` has not included `kunit_try_catch` before.
`gen_bindings.rs` is auto generated by `bindgen`. `gen_bindings.rs` contains rust bindings of the Linux kernel headers or `vmlinux.h`. So `gen_bindings.rs` varies among build environments. And also some environment variables such as `KERNEL_SOURCE`, `KERNEL_VERSION` or `REDBPF_VMLINUX` affect the build process of rust bindings for the Linux kernel data structures.

Anyway, I considered upgrading `bindgen` dependency of `cargo-bpf` and `redbpf-probes` to apply the fix of `bindgen` but new package is not released yet.

----

There's a temporary fix you can try by your hands. In your `Cargo.toml` for BPF programs, put the patch section like this:
```toml
[patch.crates-io]
bindgen = { git = "https://github.com/rust-lang/rust-bindgen.git", branch = "master" }
```
And run the `cargo bpf build` command again.

**Comment by theduke** [comment]
Thanks for the extensive explanation.

I did search for issues with "try", but apparently missed it.

**Comment by theduke** [comment]
Sidenote: is there a chat somewhere for this library, like on Matrix/IRC?

**Comment by rhdxmr** [comment]
@theduke 
Previously there was a Matrix chat room but it is not used nowadays.

**Comment by rsdy** [comment]
there are some people who still hang out at redbpf:rustch.at on Matrix, but it's mostly quiet.
