### ISSUE TITLE
BTF section is miss but bpf_spin_lock need it

### ISSUE THREAD

**Issue by Sherlock-Holo** [foniod/redbpf#233]
When use `bpf_spin_lock` or `bpf_spin_unlock` in tc BPF program and load by tc, the verifier will reports

> ```
> 35: (85) call bpf_spin_lock#93
> map '' has to have BTF in order to use bpf_spin_lock
> ```

**Comment by rhdxmr** [comment]
Currently, `.BTF` section that contains BTF type records should be removed before ELF object file is loaded by `tc` utility. Because, the BTF type records that are generated by `rustc` have illegal characters in identifiers from the point of view of the Linux kernel.

So the `redbpf` crate that is userspace runtime library, parses `.BTF` section and replaces illegal characters in the identifiers with the underscore character. But `tc` does not do that for us.

**Comment by Sherlock-Holo** [comment]
the `cargo bpf` doesn't support `tc-BPF` program

and

the section

> ```
> readelf -S egress.elf
> There are 10 section headers, starting at offset 0x4f8:
> 
> 节头：
>   [号] 名称              类型             地址              偏移量
>        大小              全体大小          旗标   链接   信息   对齐
>   [ 0]                   NULL             0000000000000000  00000000
>        0000000000000000  0000000000000000           0     0     0
>   [ 1] tc_action/egress  PROGBITS         0000000000000000  00000040
>        00000000000002c0  0000000000000000  AX       0     0     8
>   [ 2] license           PROGBITS         0000000000000000  00000300
>        0000000000000004  0000000000000000   A       0     0     1
>   [ 3] version           PROGBITS         0000000000000000  00000304
>        0000000000000004  0000000000000000   A       0     0     4
>   [ 4] maps              PROGBITS         0000000000000000  00000308
>        000000000000001c  0000000000000000  WA       0     0     4
>   [ 5] .eh_frame         PROGBITS         0000000000000000  00000328
>        0000000000000030  0000000000000000   A       0     0     8
>   [ 6] .symtab           SYMTAB           0000000000000000  00000358
>        00000000000000f0  0000000000000018           9     6     8
>   [ 7] .reltc_actio[...] REL              0000000000000000  00000448
>        0000000000000020  0000000000000010           6     1     8
>   [ 8] .rel.eh_frame     REL              0000000000000000  00000468
>        0000000000000010  0000000000000010           6     5     8
>   [ 9] .strtab           STRTAB           0000000000000000  00000478
>        000000000000007f  0000000000000000           0     0     1
> Key to Flags:
>   W (write), A (alloc), X (execute), M (merge), S (strings), I (info),
>   L (link order), O (extra OS processing required), G (group), T (TLS),
>   C (compressed), x (unknown), o (OS specific), E (exclude),
>   p (processor specific)
> ```

doesn't contains .BTF, the bpf verifier need .BTF

**Comment by Sherlock-Holo** [comment]
the tc output is 

> ```
> 8 bytes struct bpf_elf_map fixup performed due to size mismatch!
> Map 'NAT_MAP' loaded as pinned!
> 
> Prog section 'tc_action/egress' rejected: Permission denied (13)!
>  - Type:         3
>  - Instructions: 88 (0 over limit)
>  - License:      GPL
> 
> Verifier analysis:
> 
> 0: (bf) r6 = r1
> 1: (61) r1 = *(u32 *)(r6 +80)
> 2: (61) r2 = *(u32 *)(r6 +76)
> 3: (bf) r8 = r2
> 4: (07) r8 += 14
> 5: (2d) if r8 > r1 goto pc+80
>  R1_w=pkt_end(id=0,off=0,imm=0) R2_w=pkt(id=0,off=0,r=14,imm=0) R6_w=ctx(id=0,off=0,imm=0) R8_w=pkt(id=0,off=14,r=14,imm=0) R10=fp0
> 6: (15) if r2 == 0x0 goto pc+79
>  R1_w=pkt_end(id=0,off=0,imm=0) R2_w=pkt(id=0,off=0,r=14,imm=0) R6_w=ctx(id=0,off=0,imm=0) R8_w=pkt(id=0,off=14,r=14,imm=0) R10=fp0
> 7: (71) r3 = *(u8 *)(r2 +13)
> 8: (67) r3 <<= 8
> 9: (71) r4 = *(u8 *)(r2 +12)
> 10: (4f) r3 |= r4
> 11: (55) if r3 != 0x8 goto pc+74
>  R1=pkt_end(id=0,off=0,imm=0) R2=pkt(id=0,off=0,r=14,imm=0) R3=inv8 R4=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R6=ctx(id=0,off=0,imm=0) R8=pkt(id=0,off=14,r=14,imm=0) R10=fp0
> 12: (bf) r7 = r2
> 13: (07) r7 += 34
> 14: (2d) if r7 > r1 goto pc+71
>  R1=pkt_end(id=0,off=0,imm=0) R2=pkt(id=0,off=0,r=34,imm=0) R3=inv8 R4=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R6=ctx(id=0,off=0,imm=0) R7_w=pkt(id=0,off=34,r=34,imm=0) R8=pkt(id=0,off=14,r=34,imm=0) R10=fp0
> 15: (71) r3 = *(u8 *)(r2 +23)
> 16: (55) if r3 != 0x6 goto pc+69
>  R1=pkt_end(id=0,off=0,imm=0) R2=pkt(id=0,off=0,r=34,imm=0) R3_w=inv6 R4=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R6=ctx(id=0,off=0,imm=0) R7_w=pkt(id=0,off=34,r=34,imm=0) R8=pkt(id=0,off=14,r=34,imm=0) R10=fp0
> 17: (07) r2 += 54
> 18: (2d) if r2 > r1 goto pc+67
>  R1=pkt_end(id=0,off=0,imm=0) R2_w=pkt(id=0,off=54,r=54,imm=0) R3_w=inv6 R4=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R6=ctx(id=0,off=0,imm=0) R7_w=pkt(id=0,off=34,r=54,imm=0) R8=pkt(id=0,off=14,r=54,imm=0) R10=fp0
> 19: (69) r1 = *(u16 *)(r7 +0)
> 20: (55) if r1 != 0xf27 goto pc+65
>  R1=inv3879 R2=pkt(id=0,off=54,r=54,imm=0) R3=inv6 R4=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R6=ctx(id=0,off=0,imm=0) R7=pkt(id=0,off=34,r=54,imm=0) R8=pkt(id=0,off=14,r=54,imm=0) R10=fp0
> 21: (61) r1 = *(u32 *)(r8 +16)
> 22: (69) r2 = *(u16 *)(r7 +2)
> 23: (67) r2 <<= 32
> 24: (4f) r2 |= r1
> 25: (7b) *(u64 *)(r10 -8) = r2
> 26: (bf) r2 = r10
> 27: (07) r2 += -8
> 28: (18) r1 = 0xffff8f62acbd0000
> 30: (85) call bpf_map_lookup_elem#1
> 31: (bf) r9 = r0
> 32: (55) if r9 != 0x0 goto pc+1
> 
> from 32 to 34: R0=map_value(id=0,off=0,ks=8,vs=16,imm=0) R6=ctx(id=0,off=0,imm=0) R7=pkt(id=0,off=34,r=54,imm=0) R8=pkt(id=0,off=14,r=54,imm=0) R9_w=map_value(id=0,off=0,ks=8,vs=16,imm=0) R10=fp0 fp-8=mmmmmmmm
> 34: (bf) r1 = r9
> 35: (85) call bpf_spin_lock#93
> map '' has to have BTF in order to use bpf_spin_lock
> processed 37 insns (limit 1000000) max_states_per_insn 0 total_states 3 peak_states 3 mark_read 2
> 
> Error fetching program/map!
> Unable to load program
> ```

**Comment by rhdxmr** [comment]
Hello @Sherlock-Holo 

Currently, `cargo-bpf` removes `.BTF` section only when the ELF object contains tc program.

https://github.com/foniod/redbpf/blob/163103210fcdeec98d8d49a32af4f81cec5e0c73/cargo-bpf/src/llvm.rs#L234-L242

Because `.BTF` section contains invalid identifier names. The Linux kernel rejects to load the `.BTF` section generated by `rustc`.

RedBPF supports BTF by replacing invalid identifier names with valid one when parsing and loading the BTF in runtime. But in tc program case, `tc` utility directly loads BTF without correcting identifier names so it fails to load the BTF. To prevent this situation, `cargo-bpf` removes `.BTF` section beforehand.

I understand the problem you struggle with and I think this problem can be solved. The solution would be that correcting the problematic `.BTF` section by `cargo-bpf` while compiling the ELF object file.

I will try this to fix the problem, but I can't make sure the due date.
And thank you for letting me know of this problem. I hope you find workaround for the present.. and RedBPF will support BTF for tc soon.

**Comment by rhdxmr** [comment]
@Sherlock-Holo
I am working on this issue. I am currently tweaking RedBPF and I succeeded in using `bpf_spin_lock` with `tc`.
But there are some issues remained so the code is not ready to be committed yet.

The first issue is that `tc` command does not support recent version of BTF records. It has not updated BTF related code over for 3 years. Even if some identifier names generated by `rustc` are fixed by RedBPF to make the BTF pass the BPF verifier, `tc` rejects the BTF. In particular, tc does not know of `BTF_KIND_VAR`, `BTF_KIND_DATASEC`. These are relatively new BTF types but `tc` just rejects entire BTF info because of those types.
Currently, `tc` is integrating `libbpf` as a replacement of its lagacy BPF related code. But most linux distros do not support `tc` that makes use of `libbpf` yet. The new code just exists at its git repository.

To solve this issue, I am going to remove particular BTF records that are unknown to tc command.

**Comment by rhdxmr** [comment]
@Sherlock-Holo 
I just sent a PR that solves your issue.
* #241
