### ISSUE TITLE
Error when loading TC prog: invalid relo against '' in special section 0x0; forgot to initialize global var?..

### ISSUE THREAD

**Issue by d0u9** [foniod/redbpf#249]
```rust
#![no_std]
#![no_main]

use redbpf_probes::kprobe::prelude::*;
use redbpf_probes::tc::prelude::*;

program!(0xFFFFFFFE, "GPL");

#[map(link_section = "maps")]
pub static mut blocked_packets: TcHashMap<u8, u32> =
    TcHashMap::<u8, u32>::with_max_entries(1024, TcMapPinning::ObjectNamespace);

#[tc_action]
fn ingress(skb: SkBuff) -> TcActionResult {
    unsafe {blocked_packets.set(&0x15_u8, &0x15_u32); }

    Ok(TcAction::Ok) 
}
```

Fairly a simple script that I want to test shared maps until I got such an error:

```
libbpf: prog 'outer_ingress': invalid relo against '' in special section 0x0; forgot to initialize global var?..
```

How could I fix this...

**Comment by d0u9** [comment]
If I change from `TcHashMap<u8, u32>` to `TcHashmap<u8, u8>`, the problem is gone.

it is weird.

**Comment by rhdxmr** [comment]
Hi @d0u9 

You can not do this in tc program
```rust
blocked_packets.set(&0x15_u8, &0x15_u32);
```
Because, 0x15 is the data located in the .rodata section.
And &0x15 gets a reference of the data.
But tc utility does not support data relocation so it fails to load the BPF program that requires relocation.

A workaround is introducing local variable and getting a reference of it.

```rust
let key = 0x15_u8;
let val = 0x15_u32;
blocked_packets.set(&key, &val)
```

**Comment by d0u9** [comment]
@rhdxmr get it, thanks. :)
